schema_version: 20180708
name: image-processor
version: 0.0.101
runtime: docker
format: http-stream
memory: 1024
timeout: 300
idle_timeout: 300
config:
  DETECT_SENSITIVITY: "0.3"
  IS_DOCKER4MAC_LOCAL: "true"
expects:
  config:
  - name: DETECT_SENSITIVITY
    required: true
  - name: TWITTER_CONSUMER_KEY
    required: true
  - name: TWITTER_CONSUMER_SECRET
    required: true
  - name: TWITTER_ACCESS_TOKEN_KEY
    required: true
  - name: TWITTER_ACCESS_TOKEN_SECRET
    required: true
  - name: IS_DOCKER4MAC_LOCAL
    required: false
  - name: SLACK_API_TOKEN
    required: true
  - name: SLACK_CHANNEL
    required: true
triggers:
- name: image-processor
  type: http
  source: /image-processor
