apiVersion: v1
kind: Service
metadata:
  name: oci-proxy
  labels:
    app: oci-proxy
spec:
  type: LoadBalancer
  ports:
  - name: oci-proxy
    port: 9999
    targetPort: 9999
  selector:
    app: oci-proxy
