apiVersion: apps/v1beta1
kind: Deployment
metadata:
    name: oci.proxy
    labels:
        app: oci.proxy
spec:
    replicas: 1
    selector:
        matchLabels:
            app: oci.proxy
    template:
        metadata:
          labels:
            app: oci.proxy
        spec:
            restartPolicy: Always
            containers:
              - name: oci-proxy-app
                image: denismakogon/oci-proxy:0.0.1
                ports:
                - containerPort: 8080
                readinessProbe:
                  httpGet:
                    path: /ping
                    port: 8080
                  initialDelaySeconds: 3
                  periodSeconds: 3
                env:
                  - name: OCI_COMPARTMENT
                    valueFrom:
                      configMapKeyRef:
                        name: oci.proxy
                        key: compartment
                  - name: OCI_TENANCY
                    valueFrom:
                      configMapKeyRef:
                        name: oci.proxy
                        key: tenancy
                  - name: OCI_USER
                    valueFrom:
                      configMapKeyRef:
                        name: oci.proxy
                        key: user
                  - name: OCI_REGION
                    valueFrom:
                      configMapKeyRef:
                        name: oci.proxy
                        key: region
                  - name: OCI_FINGERPRINT
                    valueFrom:
                      configMapKeyRef:
                        name: oci.proxy
                        key: fingerprint
                  - name: OCI_KEY
                    valueFrom:
                      configMapKeyRef:
                        name: oci.proxy
                        key: key
                  - name: OCI_KEY_PASS
                    valueFrom:
                      configMapKeyRef:
                        name: oci.proxy
                        key: key_pass
                  - name: FN_INVOKE_ENDPOINT
                    valueFrom:
                      configMapKeyRef:
                        name: oci.proxy
                        key: invoke_endpoint
