schema_version: 20180708
name: word-generator
version: 0.0.13
runtime: go
entrypoint: ./func
format: http-stream
memory: 256
triggers:
- name: word-generator-trigger
  type: http
  source: /word-generator-trigger
